### ISSUE TITLE
startup requires a TTY

### ISSUE THREAD

**Issue by ddidier** [envygeeks/docker-ubuntu#1]
Hi,

I'm using [jekyll/stable](https://registry.hub.docker.com/u/jekyll/jekyll/) which is based on this image. I need to pass a command to the script (`jekyll build`) with no allocated TTY, i.e. without the `-t` Docker argument.

This is working:

    docker run --rm --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/stable jekyll build

But this is not working:

    docker run --rm --volume=$(pwd):/srv/jekyll -i -p 127.0.0.1:4000:4000 jekyll/stable jekyll build

Got:

    # /usr/bin/startup: line 97: /dev/tty: No such device or address

I'm no Bash expert but if I replace

    exec 1>/dev/tty

with

    if [ "$TERM" == "xterm" ]
    then
      exec 1>/dev/tty
    fi

then both cases work

**Comment by envygeeks** [comment]
I'm fixing this now, I didn't see that ticket. For some reason Github didn't subscribe me to my own repo so I didn't see that ticket.

**Comment by envygeeks** [comment]
Fixed with https://github.com/envygeeks/docker-ubuntu/commit/2732690aaa2ed38b01a77f3842879c1058efa92e

**Comment by ddidier** [comment]
That's working, thanks!

**Comment by envygeeks** [comment]
Great!  Thanks for reporting the issue.
